services:
  web:
    image: slash
    build:
      context: .
      args:
        - NODE_ENV
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - '~/dockers_data/web/logs:/logs'
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  proxy:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/ssl
